services:
  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=fr,en,ar
      - LT_UPDATE_MODELS=true
    volumes:
      - lt_data:/home/libretranslate/.local

volumes:
  lt_data: